### ISSUE TITLE
empty good, bad, gray files after split

### ISSUE THREAD

**Issue by sengoku93** [avallonking/ForestQC#2]
Hi,

I have run your test code to see if ForestQC was successfully installed and it ended up working. Next, I just wanted to take one of my own vcf files just to see if ForestQC would work before I use a larger set. I only used arguments for the ForestQC commands that are required. I did not add any of the optional arguments. Computing outliers, running ForestQC stat, and compute_gc worked. However, after trying to split I end up with empty good, bad, gray files. Do you have any suggestions why this might be the case? Thank you!

Best,
Kristofer

**Comment by avallonking** [comment]
Hi Kristofer,

Do your VCF files contain the information about the genotype of each sample? Like the last three columns below:
```
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT NA00001 NA00002 NA00003
20 14370 rs6054257 G A 29 PASS NS=3;DP=14;AF=0.5;DB;H2 GT:GQ:DP:HQ 0|0:48:1:51,51 1|0:48:8:51,51 1/1:43:5:.,.
20 17330 . T A 3 q10 NS=3;DP=11;AF=0.017 GT:GQ:DP:HQ 0|0:49:3:58,50 0|1:3:5:65,3 0/0:41:3
20 1110696 rs6040355 A G,T 67 PASS NS=2;DP=10;AF=0.333,0.667;AA=T;DB GT:GQ:DP:HQ 1|2:21:6:23,27 2|1:2:0:18,2 2/2:35:4
20 1230237 . T . 47 PASS NS=3;DP=13;AA=T GT:GQ:DP:HQ 0|0:54:7:56,60 0|0:48:4:51,51 0/0:61:2
```

Could you show me some lines in the files output by "ForestQC stat"?

Best,
Albert

**Comment by avallonking** [comment]
And did you provide your thresholds of the filters?

**Comment by sengoku93** [comment]
Hi,

Here are the first couple lines from the .tsv generated after ForestQC stat:

chr1:10611      chr1    10611   C       G       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.6459999999999999
chr1:99072      chr1    99072   C       G       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.40299999999999997
chr1:658195     chr1    658195  A       G       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.604
chr1:847283     chr1    847283  C       T       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.525
chr1:926354     chr1    926354  G       A       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.473
chr1:935938     chr1    935938  C       G       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.7559999999999999
chr1:939717     chr1    939717  C       G       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.637
chr1:980882     chr1    980882  G       A       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.623
chr1:1015718    chr1    1015718 G       C       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.669
chr1:1055308    chr1    1055308 C       G       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.561
chr1:1176156    chr1    1176156 C       G       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.68
chr1:1224751    chr1    1224751 T       C       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.698
chr1:1393643    chr1    1393643 G       A       NA      NA      NA      NA      NA      NA      NA      NA      NA      0.0     NA      NA      NA      0.499

Regarding thresholds, I used the the user_defined thresholds from the example (user_thresholds.tsv). Regarding Genotype information, below is a line copied over from .vcf:
1	10611	.	C	G	10.4238	PASS	SOMATIC;VT=SNP;mutect_SCORE=10.4238;UAC=11,0,9,4	mutect_GT:mutect_AD:mutect_BQ:mutect_DP:mutect_FA:SS	0:11,0:.:11:0:0	0/:9,4:30:13:0.308:2

Please let me know if you need any other information. Thank you for your help!

**Comment by avallonking** [comment]
I updated the software. You can do `conda update forestqc -c avallonking` to upgrade it.

**Comment by avallonking** [comment]
And please do not use any files in example for the analysis of real data. They are only for testing. So do not use user_defined thresholds from the example for real data. I think you could leave it blank. The default should work well.
