### ISSUE TITLE
A problem of set_outlier

### ISSUE THREAD

**Issue by Soap4** [avallonking/ForestQC#3]
Hi,I want to ask a problem of set_outlier.
when I perfrom set_outlier , I only have the result of Outlier_GQ threshold, my result of Outlier_DP threshold is NA.   the vcf files come from GATK.
the reaslt is:
Outlier_DP threshold:
Outlier_GQ threshold: 0

**Comment by avallonking** [comment]
Could you send me the VCF file used for "set_outlier"? You can just give me the first several hundreds of lines of the VCF file.

**Comment by Soap4** [comment]
ok! thank you very much !


------------------ 原始邮件 ------------------
发件人: "Albert Lee"<notifications@github.com>;
发送时间: 2019年7月5日(星期五) 晚上10:57
收件人: "avallonking/ForestQC"<ForestQC@noreply.github.com>;
抄送: "??"<674335732@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [avallonking/ForestQC] A problem of set_outlier (#3)




Could you send me the VCF file used for "set_outlier"? You can just give me the first several hundreds of lines of the VCF file.
