### ISSUE TITLE
Python version for ForestQC

### ISSUE THREAD

**Issue by smeeta** [avallonking/ForestQC#6]
Hi avallonking,

I was trying to install ForestQC using conda as suggested in the wiki of this doc. The package failed and in specifications it shows that following 

forestqc -> python[version ='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

I have python =3.8 
Is it that forestqc can run only in python < 3.8 ? Is there any other way out besides downgrading my python version.

Thank you. 
regards
Smeeta

**Comment by avallonking** [comment]
Hi Smeeta, 

Sorry for the late reply. I will try making the package and uploading it using Anaconda with Python 3.8. I will let you know once it is finished. I think it could take a day.

Best regards,
Albert

**Comment by avallonking** [comment]
Hi Smeeta,

I have uploaded ForestQC package for Python 3.8. Can you try installing it from Anaconda? You should be able to install it by doing `conda install forestqc -c avallonking`.

If you have any additional questions, please let me know.

Best regards,
Albert

**Comment by smeeta** [comment]
Dear Albert,

Thanks a million ! :) Awesome. I managed to install it via conda and run the ForestQC -h  to check for installation.  

All Good !

(base) smeetas-MacBook-Air:~ smeeta$ ForestQC -h
ForestQC v1.1.5.4 by Jae Hoon Sul Lab at UCLA
--Quality control on genetic variants from next-generation sequencing data using random forest

usage: ForestQC [-h] {stat,split,classify,set_outlier,compute_gc} ...

positional arguments:
  {stat,split,classify,set_outlier,compute_gc}
                        ForestQC command help
    stat                variants statistics help
    split               variants splitting help
    classify            variants classification help
    set_outlier         set outlier help
    compute_gc          compute GC content help

optional arguments:
  -h, --help            show this help message and exit

Thank you once again. Have a lovely weekend ahead :) 


regards
Smeeta
