### ISSUE TITLE
mutil-allele may split failed

### ISSUE THREAD

**Issue by magower** [avallonking/ForestQC#9]
I found that the split module will miss some multiple alleles.

```
ForestQC stat -i vcf -o stat.tsv -c gc_content_hg19.tsv --dp 14 --gq 60
ForestQC split -i stat.tsv -o part.tsv
grep -w 9770690 stat.tsv bad.part.tsv good.part.tsv gray.part.tsv | cut -f 1-5
```

> stat.tsv:chr1:9770690   chr1    9770690 CAG     C
> stat.tsv:chr1:9770690   chr1    9770690 C       CAG
> good.part.tsv:chr1:9770690      chr1    9770690 C       CAG

As mentioned above, the amount of variation does not correspond.
`wc -l stat.tsv bad.part.tsv good.part.tsv gray.part.tsv`

>    48008 stat.tsv
>      3289 bad.part.tsv
>    30420 good.part.tsv
>    14036 gray.part.tsv
>    95753 total

I am very grateful, If you can get a effective reply, thank you again for the software you provided.

**Comment by magower** [comment]
I tried an effective solution for reference:
adjustment script `data_preprocessing.py`  # grey variants
```
    grey = variants[~variants['RSID'].isin(good['RSID'])]
    grey = grey[~grey['RSID'].isin(bad['RSID'])]
```
as
```
    grey = variants.append([good, bad])
    grey = grey.drop_duplicates(subset=['RSID', 'CHR', 'POS', 'REF', 'ALT'], keep=False)
```

**Comment by avallonking** [comment]
Hi magower,

Sorry for the late reply. And thank you for your suggestion! That's a great solution to this issue. I have made the changes. Please do `conda update forestqc -c avallonking` to update the ForestQC software. This bug should be fixed. 

Best regards,
Albert
